name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: use-nodejs-20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: install-deps
      run: npm install
    - name: build-deb-rpm
      run: npm run make
    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-rpm-builds     # Name of the artifact
        path: out/make/        # Path to the build output directory
